FROM python:3.12

WORKDIR /DjangoProject

COPY . .

RUN pip install django

RUN pip install python-decouple

RUN pip install psycopg2

EXPOSE 3000

CMD [ "python", "manage.py", "runserver", "0.0.0.0:3000" ]